#import "template.typ": *
#import "@preview/ouset:0.2.0": *
#import "@preview/physica:0.9.5": *
#import "@preview/diagraph:0.3.6": raw-render

= Exercise 12

== Recap: uniform integrability

$M$ is a local martingale null at 0.

- if $M$ is continuous, then $tau_n := inf{t >= 0 : |M_t| > n} => |M^(tau_n)| <= n.$
- if $M$ is a RCLL martingale, then $sigma_n := inf{t>=0: |M_t| > n} and n$

  $=> sup_(t>0)|M^(sigma_n)| &= sup_(0<=t<=sigma_n) |M_t| \
  &= max{sup_(0<=t < sigma_n) |M_t|, |M_(sigma_n)| } \
  &<= max{n, |M_sigma_n|}.
  $

== Prior exam question

$(Omega, cal(F), P)$, $W$ is a Brownian motion, $FF$.

1. Show that $X_t := exp(W_t + t/2) + exp(W_t - t/2)$ satisfies an SDE _(will be given during the exam but can be derived)_

_Solution sketch_. Apply Itô's formula: $f(t, x) := exp(x + t/2) + exp(x - t/2).$

$
dd(X_t) &= (1/2 exp(W_t + t/2) - 1/2 exp(W_t - t/2))dd(t) + X_t dd(W_t) + 1/2 X_t dd(t) \
&= X_t dd(W_t) + exp(W_t + t/2) dd(t) quad P"-a.s.", X_0 = 2.
$

2. Let $f: RR->RR$ be a convex function.  Show that $Y_t := f(integral_0^t W_s^2 dd(W_s))$ is a submartingale if $Y$ is integrable.

_Solution sketch_. 

1. Take $tau_n:=n$.
- $integral_0^t integral W_s^2 dd(W_s)$ is a true martingale on $[|0, tau_n|] = [0, n] times Omega$.
- $integral_0^t integral W_s^2 dd(W_s)$ is a true martingale on $[0, +infinity)$.
2. Jensen's inequality.
- $Y$ is adapted: the stochastic integral is predictable due to the integrator and integrand are both predictable.  $f$ is measurable.
- apply the Jensen's inequality.

== Another one.

$mu$ and $sigma$ are two continuous adapted processes. Let $X$ be:

$
  dd(X_t) = X_t (mu_t dd(t) + sigma_t dd(W_t)), X_0 = 1.
$

Show that $Y_t := X_t exp(-integral_0^t mu_s dd(s))$ is a local martingale.

_Solution sketch_.  Two possible ways:

1. apply Itô and find the SDE satisfied by $Y$. If the finite variation part ("$dd(t)$" part) is zero, then it is a local martingale.

  Let $Y_t = X_t Z_t$, where $Z_t = exp(-integral_0^t mu_s dd(s))$. Find the SDE satisfied by $Z$: $dd(Z_t) = -mu_t Z_t dd(t)$.

  _Note: $mu$ is a finite variation process, so no $dd(W_s)$ term!_
  
  Then the SDE for $Y$ is

  $
    dd(Y_t) &= X_t dd(Z_t) + Z_t dd(X_t) + dd(\[X\, Z]_t) \
    &= -X_t mu_t Z_t dd(t) + Z_t X_t (mu_t dd(t) + sigma_t dd(W_t))\
    &= Y_t sigma_t dd(W_t).
  $
  
  Hence $Y_t = cal(E)(integral_0^dot sigma_s dd(W_s))_t.$

2. unique solution $X_t = cal(E)(integral_0^dot mu_s dd(s) + integral_0^dot sigma_s dd(W_s))_t = exp(integral_0^t mu_s dd(s) + integral_0^t sigma_s dd(W_s) - 1/2 integral_0^t sigma_s^2 dd(s)).$

  Hence $Y_t = exp(integral_0^t sigma_s dd(W_s) - 1/2 integral_0^t sigma_s^2 dd(s)) = cal(E)(integral_0^dot sigma_s dd(W_s))_t.$
  
  _Later we'll see that the stochastic exponential is a local martingale iff the value inside is a local martingale._
  
== Another one.

Find $c in RR$ and $(psi_t)_(t in [0, T])$ s.t. $W_T^2 = c + integral_0^T psi_s dd(W_s)$.

_Solution sketch_.  Apply Itô to $f(x) = x^2, x = W.$

$
  W_T^2 &= W_0^2 + integral_0^T 2W_s dd(W_s) + 1/2 integral_0^T 2 dd(s) \
  &= integral_0^T 2W_s dd(W_s) + T.
$

== Another one.

$(Omega, cal(F), P)$ with $S$ a semimartingale, $FF$ is the $P$-augmented filtration generated by $W$.  $dd(S_t) = mu_t dd(t) + sigma dd(W_t), mu_t$ is a continuous adapted process, $sigma > 0$.

Find $Q approx P$ on $cal(F)_T$ s.t. $S$ is a $Q$-local martingale. 

_Solution sketch_. $P$ is positive, hence the density process $Z_t = cal(E)(L)_t$ is a $P$-local martingale iff. $L$ is a $P$-local martingale. 

Take the martingale representation of $L$ under the $P$-augmented filtration wrt. BM $FF$: 
$
L_t = integral_0^dot alpha_s dd(W_s)_t, alpha in L^2_"loc" (W).
$

Use Girsanov: $W$ is a $P$-BM $=> W^Q_t = W_t - al L, W ar_t = W_t - integral_0^t alpha_s dd(s).$ 

$
  dd(S_t) = (mu_t + sigma alpha_t) dd(t) + sigma dd(W_t^Q).
$

Since $S_t$ is a $Q$-local martingale, $mu_t + sigma alpha_t = 0 => alpha_t = -mu_t / sigma => dd(S_t) = sigma dd(W_t^Q)$.