#import "template.typ": *
#import "@preview/physica:0.9.5": *
#import "@preview/diagraph:0.3.6": raw-render

= Exercise 8

== Recap: definition of BM

#definition[
  Take a probability space $(Omega, cal(F), P)$ with a filtration $FF = (cal(F)_t)_(t>=0)$ with the usual conditions.  A *Brownian motion* is an $FF$-adapted process s.t.
  - $W_0 = 0 quad P$-a.s.;
  - contiguous trajectories $P$-a.s.;
  - $W_t - W_s perp cal(F)_s, ~ cal(N)(0, t-s)$ given $t >= s$.
]

== Hints

*Ex. 8.1 (a).* $Z_t$ is Gaussian.  $E[Z_t] = 0, E[Z_t Z_s] = E[W_s^2]$ given $s <= t$.  Need to prove that $Z$ does not have independent increments in $FF$.

If we consider the natural filtration generated by $Z$:

$
  GG=(cal(G)_t)_(t >= 0) "s.t." cal(G)_t = sigma(Z_u : u <= t)
$

$Z$ *is indeed* a Brownian motion under $GG$.  We can show $Z_t - Z_s perp cal(G)_s$ by showing $E[(Z_t - Z_s) Z_u] = 0$ given $t >= s >= u$ (since $Z$ is Gaussian).

*Ex. 8.1 (b).* is a past exam question.  Use the rescaling property!

*Ex. 8.2.* The law of large numbers for Brownian motions:

$
  lim_(t->infinity) W_t/t = 0.
$

The (global) law of iterated logarithm:
$
  limsup_(t->infinity) W_t/sqrt(2t log log t) = 1,\
  liminf_(t->infinity) W_t/sqrt(2t log log t) = -1.
$

The (local) law of iterated logarithm:
$
  limsup_(t arrow.b 0) W_t/sqrt(2t log log 1/t) = 1,\
  liminf_(t arrow.b 0) W_t/sqrt(2t log log 1/t) = -1.\
$

== Extra exercises

*Ex. 1.* Let $f: [0, +infinity) -> RR$ be a $L^2$-function.  Let $X = (X_t)_(t>=0)$ s.t. $X_t = f(t) W_t + H$ for $H$ is $cal(F)_0$-measurable r.v. s.t. $~ cal(N)(0, 1)$.
- Compute the distribution of $X_t$.

  _Solution sketch_.  Prove that $f(t)W_t$ and $H$ are independent.  $<=> W_t$ and $H$ are independent:
  $
    W_t = W_t - W_0 perp cal(F)_0
  $

  _Note: $cal(F)_0$ cannot be trivial here, or $H$ cannot be $~cal(N)(0,1)$._

  $X_t$ is the sum of two independent Gaussian r.v. $=> X_t$ is Gaussian.  $X_t ~ cal(N)(0, 1+ f^2(t)t)$.

- Compute $E[X_t X_s]$ for $s <= t$.

  _Solution sketch_. 
  $
    E[X_t X_s] &= E[f(t)W_t H + H^2 + f(s)W_s f(t)W_t + H f(s)W_s] \
    &= 0 + 1 + f(s)f(t)E[W_s W_t] + 0 \
    &= 1 + f(s)f(t) E[W_s E[W_t | cal(F)_s]] = 1 + f(s)f(t) E[W_s (W_t - W_s + W_s)] \
    &= 1 + f(s)f(t)s.
  $
  
*Ex. 2.* Let $A := integral_0^1 bb(1)_{W_u > 0} dd(u)$.  Show that $P[A>0] =1.$

_Solution sketch._ Use the local LIL.  $limsup_(t arrow.b 0) W_t / sqrt(2t log log 1/t) = 1$ and $liminf dot.op = -1$ means:

$
  exists (t_n)_(n in NN) arrow.br 0 "s.t." W_t_n >= (1-epsilon) sqrt(2 t_n log log 1/t_n),\
  exists (s_n)_(n in NN) arrow.br 0 "s.t." W_t_n <= -(1-epsilon) sqrt(2 s_n log log 1/s_n),\
$

That is, $W_s_n < 0 < W_t_n$.  Since $W$ is contiguous, there exists a neighborhood $in [0, 1]$ with non-zero measure s.t. $bb(1)_{W_t > 0}$, hence $P[A > 0] = 1.$