#import "../template.typ": *
#import "exsheet-template.typ": *
#import "@preview/physica:0.9.5": *
#import "@preview/ouset:0.2.0": *
#import "@preview/diagraph:0.3.6": raw-render

#show: exsheet.with(13)

#exercise() Let $W = (W_t)_(t>=0)$ be a Brownian motion on a probability space $(Omega, cal(F), P)$.  Let $FF^W = (cal(F)_t^W)_(t in [0, infinity])$ be the $P$-augmented filtration generated by $W$.  For each of the following random variables, determine its decomposition as given in Itô's representation theorem:

1. $W_T$.
  #attempt[
    Let $f(x) := x => f'(x) = 1, f''(x) = 0.$  Apply Itô's formula:

    $
      dd(W_t) &= 1 dd(W_t) + 1/2 0 dd(W_s) \
      W_T &= W_0 + integral_0^T 1 dd(W_s) = integral_0^infinity bb(1)_{s <= T} dd(W_s).
    $
    We have $E[W_T] = 0, psi_t = bb(1)_{t <= T}.$
  ]
  
2. $cos(W_T)$.
  #attempt[
    Let $f(x, t) := exp(t/2) cos(x) => f_x = -sin(x) exp(t/2), f_t = 1/2 exp(t/2) cos(x), f_(x x) = -cos(x) exp(t/2).$  Apply Ito's formula:

    $
      dd(exp(t/2) cos(W_t)) &= -sin(W_t) exp(t/2) dd(W_t) + (1/2 exp(t/2) cos(x) - 1/2 cos(x) exp(t/2)) dd(t) \
      &= -sin(W_t) exp(t/2) dd(W_t) \
      => exp(T/2) cos(W_T) &= 1 + integral_0^T -sin(W_s) exp(s/2) dd(W_s) \
      => cos(W_T) &= exp(-T/2) + integral_0^T -sin(W_s) exp(-(T-s)/2) dd(W_s).
    $
    We have $E[cos(W_T)] = exp(-T/2), psi_t = -sin(W_t) exp(-(T-t)/2) bb(1)_{t <= T}.$
  ]
  
#exercise() Let $T>0$ denote a fixed time horizon.  Let $W = (W_t)_(t in [0,T])$ be a Brownian motion on a probability space $(Omega, cal(F), P)$ and $FF^W = (cal(F)_t^W)_(t in [0, T])$ the $P$-augmented filtration generated by $W$.  Consider the Black-Scholes model, where the undiscounted bank account price process
$tilde(S)^0 = (tilde(S)^0_t)_(t in [0,T])$
and the undiscounted stock price process
$tilde(S)^1 = (tilde(S)^1_t)_(t in [0,T])$
satisfy
$
  dd(tilde(S)^0_t) = tilde(S)^0_t r dd(t) quad "and" quad dd(tilde(S)^1_t) = tilde(S)^1_t (mu dd(t) + sigma dd(W_t)) quad P-"a.s.",
$
where $r, mu in RR, sigma > 0, tilde(S)^0_0 = 1$ and $tilde(S)^1_0 > 0$ is a constant.

1. Prove that the discounted stock price process $S^1 := tilde(S)^1/tilde(S)^0$ solves
  $
    dd(S^1_t) = S^1_t ((mu - r)dd(t) + sigma dd(W_t)) quad P-"a.s."
  $
  #attempt[
    Let $f(x, y) = x/y => f_x = 1/y, f_y = -x/y^2, f_(x x)=0, f_(x y) = -1/y^2, f_(y y) = 2x/y^3$.  Apply Ito's formula, given processes $X, Y$:
    $
      dd(X/Y) &= dd(X)/Y - (X dd(Y))/Y^2 + 1/2 f_(x x) dd(\[X]) + 1/2 f_(y y) dd(\[Y]) + f_(x y) dd(\[X\,Y]).
    $
    
    Let $X := tilde(S)^1, Y := tilde(S)^0 => [Y] = [X, Y] = 0$. Hence
    $
      dd(S) = dd(tilde(S)^1/tilde(S)^0) &= dd(tilde(S)^1)/tilde(S)^0 - (tilde(S)^1 dd(tilde(S)^0))/(tilde(S)^0)^2 \
      &= S ((mu - r) dd(t) + sigma dd(W_t)). quad qed
    $
  ]
  
2. Let $Z^lambda := cal(E)(L^lambda)$, where $L^lambda := -lambda W$.  Define the probability measure $Q_lambda$ by
  $
    dd(Q_lambda)/dd(P) = Z^lambda_T.
  $
  Prove that the process $W_lambda := (W_t + lambda t)_(t in [0,T])$ is a Brownian motion under $Q_lambda$.
  #attempt[
    $Q approx P$ with a density process $Z^lambda$.  Apply Girsanov for $nu = -lambda$:
    $
      W_lambda = W - al integral nu dd(W), W ar = W - integral nu dd(s) = W + lambda t
    $ is a $Q$-Brownian motion. $qed$
  ]
  
3. Prove that for a (unique) good choice of $lambda$, the discounted stock price process $S^1$ is a $Q_lambda$-martingale.
  #attempt[
    Write $dd(W_t)$ with $dd(W_lambda)$:
    $
      dd(W_t) = dd(W_lambda) - lambda
    $

    For $S^1$ to be a $Q_lambda$-martingale, its drift term when represented with $W_lambda$ needs to be zero:

    $
      dd(S^1_t) &= S^1_t sigma (dd(W_t) + (mu-r)/sigma dd(t))\
      &= S^1_t sigma (dd(W_lambda) + (((mu-r)/sigma) - lambda)dd(t)) \
      => lambda &= (mu-r)/sigma. quad qed
    $
  ]
  
#exercise() Let $T>0$ denote a fixed time horizon.  Let $W = (W_t)_(t in [0,T])$ be a Brownian motion on a probability space $(Omega, cal(F), P)$ and $FF^W = (cal(F)_t^W)_(t in [0, T])$ the $P$-augmented filtration generated by $W$.  Consider the Black-Scholes model, where the undiscounted bank account price process
$tilde(S)^0 = (tilde(S)^0_t)_(t in [0,T])$
and the undiscounted stock price process
$tilde(S)^1 = (tilde(S)^1_t)_(t in [0,T])$
satisfy
$
  dd(tilde(S)^0_t) = tilde(S)^0_t r dd(t) quad "and" quad dd(tilde(S)^1_t) = tilde(S)^1_t (mu dd(t) + sigma dd(W_t)) quad P-"a.s.",
$
where $r, mu in RR, sigma > 0, tilde(S)^0_0 = 1$ and $tilde(S)^1_0 > 0$ is a constant.  Using the notation of Exercise 13.2, denote $Q^* := Q_(lambda^*)$, where $lambda^*$ is the unique value of $lambda$ making $Q_lambda$ an equivalent martingale measure for $S^1 := tilde(S)^1/tilde(S)^0$, that is, $lambda^* := (mu-r)/sigma$.

1. Hedge the _square option_, i.e., find a self-financing strategy $phi hat(=) (V_0, theta.alt)$ such that
  $
    V_0 + integral_0^T theta.alt_t dd(S^1_t) = (tilde(S)^1_T)^2/tilde(S)^0_T quad P"-a.s."
  $
  #attempt[
    $H = (tilde(S)^1_T)^2/tilde(S)^0_T = tilde(S)^0_T (S^1_T)^2$.

    Let $f(x, y) = x^2 y => f_x = 2x y, f_y = x^2, f_(x x) = 2y, f_(x y) = 2x, f_(y y) = 0.$  Hence
    $
      dd(((S^1_t)^2 (tilde(S)^0_t))) = 2 S^1_t tilde(S)^0_t dd(S^1_t) + (S^1_t)^2 dd(tilde(S)^0_t) + tilde(S)^0_t dd(\[S^1]_t)
    $
    $theta_t$ is the coefficient of $dd(S^1_t)$, hence $theta_t = 2S^1_t tilde(S)^0_t, V_0 = (tilde(S)^1_0)^2$.
  ]
  
2. Hedge the _inverted option_, i.e., find a self-financing strategy $phi hat(=) (macron(V_0), macron(theta.alt))$ such that
  $
    macron(V_0) + integral_0^T macron(theta.alt_t) dd(S^1_t) = 1/(tilde(S)^0_T tilde(S)^1_T) quad P"-a.s."
  $
  
  #attempt[
    $macron(H) = 1/(tilde(S)^0_T tilde(S)^1_T) = 1/((tilde(S)^0_T)^2 S^1_T)$.

    Let $f(x, y) = 1/(x y^2) => f_x = -1/(x^2 y^2), f_y = -2/(x y^3), f_(x x) = 2/(x^3 y^2).$  Hence
    $
      dd(1/(S^1_t (tilde(S)^0_t)^2)) = -1/((S^1_t)^2 (tilde(S)^0_t)^2) dd(S^1_t) + "finite variation term".
    $
    $theta_t$ is the coefficient of $dd(S^1_t)$, hence $theta_t = -1/(S^1_t tilde(S)^0_t)^2, V_0 = 1/(tilde(S)^1_0)$.
  ]
  