#import "../template.typ": attempt, feedback
#import "exsheet-template.typ": *
#import "@preview/physica:0.9.5": *

#show: exsheet.with(2)

#exercise() Consider a probability space $(Omega, cal(F), P)$.  Fix a finite time horizon $T in NN$, and let $r_1, ..., r_T > -1$ and $Y_1, ..., Y_T > 0$ be random variables.  Define

$ tilde(S)^0_k := product_(j=1)^k (1 + r_j) quad "and" quad tilde(S)^1_k := S_0^1 product_(j=1)^k Y_j quad "for" k=0, ..., T. $

where $S_0^1 > 0$ is constant.  We adopt the convention that the product over an empty set is 1.  Let $FF = (cal(F)_k)_(k=0,...,T)$ be the filtration given by

$ cal(F)_k := sigma(tilde(S)_0^1, tilde(S)_1^1, ..., tilde(S)_k^1). $

1. Consider the filtration $FF' = (cal(F)'_k)_(k=0,...,T)$ generated by $Y = (Y_k)_(k=1,...,T)$ and $r = (r_k)_(k=1,...,T)$ so that

  $ cal(F)'_0 := {diameter, Omega}, quad cal(F)'_k := sigma(Y_1, ..., Y_k, r_1, ..., r_k) quad "for" k=1,...,T. $

  Show that if $r$ is $FF'$-predictable, then $cal(F)'_k = cal(F)_k$ for all $k=0,...,T$.

#attempt[
  $r$ is $FF'$-predictable $=> r_k$ is $cal(F)'_(k-1)$-measurable.  To show $cal(F)'_k = cal(F)_k$, we show that $cal(F)'_k subset.eq cal(F)_k$ as well as $cal(F)_k subset.eq cal(F)'_k$.

  $cal(F)_k subset.eq cal(F)'_k$: $tilde(S)_i^1 = S_0^1 product_(j=1)^i Y_j$ is a measurable function of $(Y_1,..., Y_k)$, every set ${tilde(S)_i^1 in B}$ for any Borel $B$ is in $cal(F)'_k = sigma(Y_1, ..., Y_k, ...)$.  Hence $cal(F)_k = sigma(tilde(S)^1_0, ..., tilde(S)^1_k) subset.eq cal(F)'_k$.

  $cal(F)'_k subset.eq cal(F)_k$: we show that $Y_1, ..., Y_k, r_1, ..., r_k$ are all $cal(F)_k$-measurable.  Prove by induction:

  - base case $k=1$:

    $Y_1 = tilde(S)_1^1 \/ tilde(S)_0^1$ is $cal(F)_1$-measurable since both divisor and numerator are generators.
    
    $r_1$ is $cal(F)'_0$-measurable where $cal(F)'_0 = {diameter, Omega}$ hence $r_1$ is constant, thus $cal(F)_0$-measurable as well.

  - inductive case: $Y_1, ..., Y_(k-1), r_1, ..., r_(k-1)$ are all $cal(F)_(k-1)$-measurable.

    $Y_1, ..., Y_(k-1), r_1, ..., r_(k-1)$ holds trivially since $cal(F)_(k-1) subset.eq cal(F)_k$.

    $Y_k = tilde(S)_k^1 \/ tilde(S)_(k-1)^1$ is $cal(F)_k$-measurable since both divisor and numerator are generators.

    Since $r_k$ is $cal(F)'_(k-1)$-measurable, all generators $cal(F)'_(k-1)$ are $cal(F)_k$-measurable, hence $r_k$ is $cal(F)_k$-measurable.

  Hence $cal(F)'_k subset.eq cal(F)_k and cal(F)_k subset.eq cal(F)'_k => cal(F)'_k = cal(F)_k.  quad qed$
]

#pagebreak()

2. Consider a positive $FF$-adapted process $D = (D_k)_(k=0,...,T)$ and define

  $ dash(S)_k^i := S_k^i D_k quad "for" k=0,...,T. $

  where $S^i := tilde(S)^i \/ tilde(S)^0$ is the discounted asset price for $i=0,1$.  For any trading strategy $phi=(phi^0, theta)$, show that the discounted cost process $C(phi)$ is constant over time if and only if the cost process $dash(C)(phi)$ with

  $ Delta dash(C)_k (phi) := (phi_k^0 - phi_(k-1)^0) dash(S)_(k-1)^0 + (theta_k - theta_(k-1)) dash(S)_(k-1)^1 quad "for" k=1,...,T $

  is constant over time.

#attempt[
  
]