#import "../template.typ": attempt, feedback
#import "exsheet-template.typ": *
#import "@preview/physica:0.9.5": *
#import "@preview/ouset:0.2.0": *

#show: exsheet.with(4)

#exercise() Let $(Omega, cal(F), P)$ be a probability space with a filtration $FF = (cal(F)_k)_(k=0,...,T)$.  For a discounted asset price process $S = (S_k)_(k=0,..,T)$, show that the following are equivalent:

#[
  #set enum(numbering: "(i)")
  1. $S$ satisfies NA.
  2. For each $k=0,...,T-1$, the one-period market $(S_k, S_(k+1))$ on the probability space $(Omega, cal(F)_(k+1), P)$ with the filtration $(cal(F)_k, cal(F)_(k+1))$ satisfies NA.
]

#attempt[
  $S$ satisfies NA $<=> exists "probability measure" Q approx P$ such that $S$ is a $Q$-martingale $<=> exists Q "s.t." E_Q [S_(k+1) | cal(F)_k] = S_(k+1) quad forall k=0,...,T-1.$  This coincides with the martingale property
  for the one-period process $tilde(S)^k = (S_k, S_(k+1))$ to be a $((cal(F)_k, cal(F)_(k+1)), Q)$-martingale, which is equivalent to (ii).  $qed$
]

#exercise() Let $(tilde(S)^0, tilde(S)^1)$ be a trinomial model.  The asset price processes are given by

$  
  tilde(S)^0_(k+1) / tilde(S)^0_k = 1 + r quad "and" quad 
  tilde(S)^1_(k+1) / tilde(S)^1_k = Y_(k+1) quad quad
  "for" k = 0, 1, ..., T-1,
$

where the initial values are $tilde(S)^0_0 = 1$ and $tilde(S)^1_0 = 1$.  The random variables $(Y_k)_(k=1,...,T)$ are i.i.d.~and satisfy

$
  Y_1 = cases(
    1 + y_1 & "with probability " p_1 in (0,1)\,,
    1 + y_2 & "with probability " p_2 in (0,1)\,,
    1 + y_3 & "with probability " p_3 in (0,1)\,,
  )
$

with $p_1 + p_2 + p_3 = 1$ and $y_1 > y_2 > y_3 > -1$.  We also have $r>-1$.  We consider the filtration $FF = (cal(F)_k)_(k=0,...,T)$ generated by $tilde(S)^1$.

1. Suppose that $r <= y_3$.  Show that in this case, the market $(tilde(S)^0, tilde(S)^1)$ admits arbitrage, by explicitly constructing an arbitrage opportunity.

#attempt[
  Take the self-financing strategy $phi hat(=) (0, theta.alt)$ where $theta.alt = cases(0 "if" k != 1, 1 "if" k = 1)$.

  $ V_0(phi) = 0 < V_k (phi) = V_1(phi) = cases(
    y_1 - r "with probability" p_1,
    y_2 - r "with probability" p_2,
    y_3 - r "with probability" p_3,
  ) quad forall k = 1,...,T. $
]

2. Suppose that $y_1 > y_2 = r > y_3$ and consider an arbitrary self-financing strategy $phi hat(=) (V_0, theta.alt)$.  Show that if the total gain $G_1 (theta.alt)$ at time $T=1$ is nonnegative $P$-a.s., then $G_1 (theta.alt) = 0 quad P$-a.s.

#attempt[
  $y_1 > r > y_3 => S$ is NA, thus there exists probability measure $Q$ where $E_Q [G_1(theta.alt)] = 0.$  Since $G_1(theta.alt) >= 0 quad P$-a.s., $G_1(theta.alt) = 0 quad P$-a.s.  $qed$
]

#exercise() Consider a financial market 